name: Deploy Javadoc

on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Javadocumenntation
        uses: dev-vince/Javadoc-publisher.yml@1.0.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: docs
          java-version: 8
          target-folder: docs 
